name: CI on DAS-5

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  connect-open-vpn-and-run-ssh-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn openvpn-systemd-resolved
      - name: Connect VPN
        id: connect_vpn
        timeout-minutes: 1
        run: |
          echo "${{ secrets.OVPN_FILE}}" | base64 -d > ./cert.ovpn
          sudo openvpn --config ./cert.ovpn --daemon
          until ip -f inet addr show tun0; do sleep 5; ip a; done
          echo ::set-output name=tunnel_ip::$(ip -f inet addr show tun0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
      - name: Copy script.sh via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .github/script.sh
          target: ci4gpu-script.sh
      - name: run ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: sh ci4gpu-script.sh
          script_stop: true # Stop after first failure
      - name: kill vpn
        if: always()
        run: sudo killall openvpn